### ISSUE TITLE
batteryHandle batteryLabel

### ISSUE THREAD

**Issue by Blue68Camaro** [hannarakhsha/Fitbit-Watchface#1]
In Index.js - Lines 80, 83 and 86 - batteryHandle should be batteryLabel to match styles and index.gui references to text.
Should look like this:

if (batteryValue === "100"){
  batteryLabel.text = `${batteryValue}%`;
}
else if(batteryValue <= "99" && batteryValue >= "10"){
  batteryLabel.text = `${"  "}${batteryValue}%`;
}
else{
  batteryLabel.text = `${"   "}${batteryValue}%`;
}

**Comment by hannarakhsha** [comment]
Thank you! Changes have been made.
