### ISSUE TITLE
Battery Level and Battery.png

### ISSUE THREAD

**Issue by Blue68Camaro** [hannarakhsha/Fitbit-Watchface#2]
Battery level is to be placed inside battery png and is not. The png file is not used anywhere but listed. Does not affect operation but seemed like a lot of trouble to use the code below so it would.

// Measure the battery level and assign it to batteryValue
    const batteryLabel = document.getElementById("batteryLabel");

    let batteryValue = battery.chargeLevel; 

//Center battery level inside Battery.png
    if (batteryValue === "100"){
    batteryLabel.text = `${batteryValue}%`;
}
    else if(batteryValue <= "99" && batteryValue >= "10"){
    batteryLabel.text = `${"  "}${batteryValue}%`;
}
else{
    batteryLabel.text = `${"   "}${batteryValue}%`;
}

**Comment by hannarakhsha** [comment]
Code has been rewritten.
